hobuinc/untwine

bu/CMakeLists.txt, common/GridKey.hpp, epf/CMakeLists.txt
- cmake: find PDAL not Pdal (otherwise PDALConfig.cmake is not used)
- cmake: add pdal version check (>= 2.2 because of ThreadPool include)
- missing #includes
- missing link to pthreads
=> Compilation fixes (ubuntu 20.04, gcc 9.3.0)

.gitignore, untwine/src/api/untwine.h
=> another try

api/QgisUntwine_unix.cpp
Fixes the compilation error:
```
/usr/bin/c++    -Wno-implicit-fallthrough -Wno-int-in-bool-context -Wno-dangling-else -Wno-noexcept-type -Wall -Wextra -Wpointer-arith -Wcast-align -Wcast-qual -Wno-error=parentheses -Wno-error=cast-qual -Wredundant-decls -Wno-unused-parameter -Wno-unused-variable -Wno-long-long -Wno-unknown-pragmas -Wno-deprecated-declarations -Werror -std=gnu++11 -MD -MT CMakeFiles/qgt.dir/QgisUntwine.cpp.o -MF CMakeFiles/qgt.dir/QgisUntwine.cpp.o.d -o CMakeFiles/qgt.dir/QgisUntwine.cpp.o -c ../QgisUntwine.cpp
In file included from ../QgisUntwine.cpp:8:
../QgisUntwine_unix.cpp: In member function ‘bool untwine::QgisUntwine::stop()’:
../QgisUntwine_unix.cpp:66:11: error: ‘waitpid’ was not declared in this scope
66 |     (void)waitpid(m_pid, nullptr, 0);
| …
```
=> Fix compilation on Ubuntu 20.04

bu/Processor.cpp, epf/Epf.cpp, epf/Grid.cpp, untwine/FileDimInfo.hpp, untwine/ProgressWriter.cpp
@wonder-sk : Does the `(void)pointId;` quiet things for you?
=> Quiet compiler warning/errors.

epf/FileProcessor.cpp, untwine/MapFile.hpp
Hello :hand:
Trying to compile Untwine on Windows (Windows 10, Visual Studio 2019) I get the following:
```
Untwine.cpp
D:\ddb\untwine\untwine\MapFile.cpp(50,18): error C2039: '_open': is not a member of '`global namespace'' [D:\ddb\untwin
e\build\untwine.vcxproj]
D:\ddb\untwine\untwine\MapFile.cpp(50,53): error C2065: '_O_RDONLY': undeclared identifier [D:\ddb\untwine\build\untwin
e.vcxproj]
D:\ddb\untwine\untwine\MapFile.cpp(50,65): error C2065: '_O_RDWR': undeclared identifier [D:\ddb\untwine\build\untwine.
vcxproj]
D:\ddb\untwine\untwine\MapFile.cpp(50,23): error C3861: '_open': identifier not found [D:\ddb\untwine\build\untwine.vcx
proj]
D:\ddb\untwine\untwine\MapFile.cpp(68,46): error C3861: '_get_osfhandle': identifier not found [D:\ddb\untwine\build\un
twine.vcxproj] …
```
=> Fix compilation on Windows

api/QgisUntwine_win.cpp
`QgisUntwine_win.cpp` uses `std::min` which is defined in `<algorithm>` which isn't currently included. On Visual Studio 2017 (and I suspect other versions...) this results in a compile error.
xref: https://github.com/conda-forge/qgis-feedstock/pull/178
=> add #include <algorithm> to QgisUntwine_win.cpp

epf/Epf.cpp, epf/EpfTypes.hpp, epf/FileProcessor.cpp
Thought this had been committed long ago. Guess not.
=> Support LAS start

untwine/Untwine.cpp
Fixes #77 
First create parent output dir before creating temp sub-dir in it...
=> Fix error when running untwine not in single file mode

bu/CopcSupport.cpp, bu/Processor.cpp
=> Don't write chunks when there are no points.

CMakeLists.txt
I had laz-perf 2.1.0 but untwine from the main branch failed to compile with various build errors, so I guess 3.0.0 is the required minimum now (which compiles fine with latest untwine).
An excerpt from compile errors with laz-perf 2.1.0:
```
../bu/CopcSupport.hpp:57:14: error: ‘copc_info_vlr’ in namespace ‘lazperf’ does not name a type; did you mean ‘copc_vlr’?
```
=> Require laz-perf 3.0.0 to build untwine

epf/Epf.cpp
COPC validation ([link](https://viewer.copc.io/validator/index.html)) was identifying data which was unpacking to be outside of its bounds due to the offset not being evenly divisible by the scale factor.  For example, the following value:
```
Scale: 0.01
Offset: [215957.75236873244, 2034592.0870288194, 29.55000000000001]
Bounds (of node): [
211645.27529721166,
2033409.4779929873,
-65.85000000000036,
211739.02490434938,
2033503.2276001251,
27.8996071377328
]
Point: [211708.50236873244, 2033409.4770288193, -21.499999999999993]
```
Here, the Y-value of this point is less than the minimum-Y value of the bounds of its containing node.  It may be true that it's not strictly incorrect, but for practical purposes pinning to a neater number so the associated floating point operations with bounds …
=> Round offsets to integral values

README.md
This mini-PR adds a small note about Untwine being available on `conda-forge`. 
Feel free to close in case this is not an appropriate installation method
=> Add conda installation note

bu/CopcSupport.cpp, epf/Epf.cpp, untwine/Common.hpp, untwine/Untwine.cpp
This PR adds a `--forward_all` option. When this option is used in single file mode, and a single input las/laz file is used then the following header info are preserved:
- file source id
- global encoding (except the wkt bit)
- creation day
- creation year
- system identifier
- generating software
- offsets (scale was already preserved)
This will ultimately be used in QGIS by default so that Untwine is a transparent stage for the end user.
Also, when the `--forward_all` option is not used, the creation day/year is now correctly populated and the generating software is populated with `Untwine`
Fixes #139
=> Add option to forward laz header info

untwine/Untwine.cpp
Build with PDAL < 2.5 was failing like this:
```
/home/martin/qgis/git-master/external/untwine/untwine/Untwine.cpp: In function ‘void untwine::cleanup(const string&, bool)’:
/home/martin/qgis/git-master/external/untwine/untwine/Untwine.cpp:112:10: error: ‘regex’ is not a member of ‘std’
112 |     std::regex re("[0-9]+-[0-9]+-[0-9]+-[0-9]+.bin");
|          ^~~~~
/home/martin/qgis/git-master/external/untwine/untwine/Untwine.cpp:113:10: error: ‘smatch’ is not a member of ‘std’; did you mean ‘search’?
113 |     std::smatch sm;
|          ^~~~~~
|          search
/home/martin/qgis/git-master/external/untwine/untwine/Untwine.cpp:117:18: error: ‘regex_match’ is not a member of ‘std’
117 |         if (std::regex_match(f, sm, re))
|                  ^~~~~~~~~~~ …
```
=> Fix build with PDAL < 2.5

api/QgisUntwine.cpp, api/QgisUntwine.hpp, api/QgisUntwine_unix.cpp, api/QgisUntwine_win.cpp
In the -hopefully rare- case that untwine crashes there is no error show to the user in QGIS (see https://github.com/qgis/QGIS/issues/48307)
I wonder if this is a good approach to tackle this, by propagating the exit code from the untwine process to the `QgisUntwine::errorMessage` ...
=> Return the exit code to QgisUntwine in case of no error message but no clean exit

README.md, epf/Epf.cpp, epf/EpfTypes.hpp, epf/FileProcessor.cpp, untwine/Common.hpp, untwine/Untwine.cpp
We encountered this issue for datasets that are like: https://github.com/qgis/QGIS/issues/51862
The option to disable parsing SRS is in: https://github.com/PDAL/PDAL/pull/3818
In this PR we allow untwine to pass this option to las readers when specified and applicable only to las readers.
=> Pass `nosrs` to las reader to prevent crashing on some incorrectly set global encoding WKT flag

epf/Epf.cpp, epf/FileProcessor.cpp
This will fix issues like https://github.com/qgis/QGIS/issues/56945
Any valid reason to create an option for that and not to have it as true by default?
=> default to use_eb_vlr=true for readers.las

prep/FilePrep.cpp
This fixes the following error:
```
error: unused parameter 'scale' [-Werror,-Wunused-parameter]
351 |     auto calcScale = [](double scale, double low, double
high)
```
=> fileprep: Remove unused scale parameter in determineScale

api/QgisUntwine_win.cpp
This fixes compilation with vcpkg.
See: https://github.com/qgis/QGIS/commit/8a94723dc12b41babed8ec2c1dff4418f9424bf8
=> qgisuntwine_win: Fix startupInfo parameter

prep/FilePrep.cpp
This fixes a long standing issue, untwine is ignoring the input files' crs.
There have been related open issues in QGIS (eg https://github.com/qgis/QGIS/issues/59662), however the issue has gone some times undetected due to QGIS reading the crs from the .las/.laz file when this is loaded instead of reading it from the copc.
To replicate:
```bash
$ pdal info --metadata test/data/autzen_trim.laz
$ untwine -i test/data/autzen_trim.laz -o test/data/autzen_trim.copc.laz -s
$ pdal info --metadata test/data/autzen_trim.copc.laz
```
=> Read crs from input files

api/QgisUntwine_win.cpp, untwine/windows/stringconv.hpp
While untwine works ok with accented filenames as a command line tool, it is still failing when run within QGIS on windows.
There problem is the hard coded ANSI variants of windows calls in `QgisUntwine_win.cpp` (`STARTUPINFOA` and `CreateProcessA`).
Reverting the dirty fix from https://github.com/qgis/QGIS/commit/8a94723dc12b41babed8ec2c1dff4418f9424bf8 and using the generic `CreateProcess` while expanding the used filenames through `untwine::os::toNative()` should finally fix the issue.
=> Don't use ANSI calls in QgisUntwine

untwine/generic/progress.hpp
This has been broken for some time and only the first message would be written to the descriptor. 
`writeMessage()` would then return `false` on no error and the caller would set `m_fd` to `-1` to stop the messages.
In windows those methods just return `true` so there's no problem.
=> Fix progress descriptor for linux
